description = "Fetch and analyze GitLab/GitHub issue using git_mcp_server tools"
prompt = '''
# 🎯 Issue Analysis

**Arguments:** {{args}}

Analyze GitLab/GitHub issues with smart context understanding.

## Mode Selection

If no arguments provided ("-" or empty), show **My Issues Dashboard**:
- List issues assigned to me across configured platforms
- Show priority, status, and project context
- Allow selection for detailed analysis

If arguments provided, analyze **Specific Issue**:
- Fetch issue details from URL or platform/project/issue-id
- Provide technical analysis and requirements
- Generate implementation suggestions

## Analysis Output

**For My Issues List:**
1. **Assigned Issues** - use `list_my_issues()` to get issues assigned to current user
2. **Recent Activity** - use `list_all_issues()` for recently updated issues
3. **Priority Issues** - filter high priority or urgent items
4. **Selection Prompt** - choose issue for detailed analysis with `get_issue_details()`

**For Specific Issue:**
1. **Issue Overview** - use `get_issue_by_url()` or `get_issue_details()` for title, description, labels, priority
2. **Technical Requirements** - analyze what needs to be implemented
3. **Context Analysis** - review current codebase for related components
4. **Next Steps** - suggested approach for development

Use `/plan` after issue analysis to generate the development plan.
'''
