description = "Create pull/merge request and close related issue using git_mcp_server tools"
prompt = '''
# 🚀 Pull Request Creation

**Issue ID:** {{args}}

Create a pull/merge request and close the related issue.

## PR Creation Process

1. **Prepare Branch**
   Run git commands to add, check status, and commit changes

2. **Push to Remote**
   Push the current branch to remote repository

3. **Create Pull/Merge Request**
   Use `create_merge_request()` to create the PR/MR with:
   - Descriptive title linking to issue
   - Comprehensive description
   - Closes #[issue-id] in description
   - Appropriate labels and reviewers

4. **PR Description Template**
   ```
   ## Summary
   Implements [feature description] as requested in issue #[issue-id]

   ## Changes Made
   - [List of changes]

   ## Testing
   - [Test coverage details]

   ## Documentation
   - [Documentation updates]

   Closes #[issue-id]
   ```

5. **Final Steps**
   - Link PR to original issue (use `update_issue()` to close issue if needed)
   - Request code review via `get_merge_request_details()` for tracking
   - Monitor CI/CD pipeline
   - Address review feedback

**Workflow Complete!** From issue analysis to PR creation.
'''
